"$schema" = 'https://starship.rs/config-schema.json'

format = """
$character\
[](fg:surface bg:secondary_container)\
$username\
[](bold fg:surface bg:secondary_container)\
$directory\
[](bold fg:surface bg:secondary_container)\
$git_branch\
[](bold fg:surface bg:secondary_container)\
$kubernetes\
[](fg:secondary_container bg:surface)\
\n[  ](fg:on_surface)
"""
palette = 'matugen'

[character]
disabled = false
success_symbol = '[  ](bold fg:on_primary bg:primary)[](fg:primary)'
error_symbol = '[  ](bold fg:on_error bg:error)[](fg:error)'

[username]
show_always = true
style_user = "fg:on_secondary_container bg:secondary_container"
style_root = "fg:on_secondary_container bg:secondary_container"
format = '[ $user ]($style)'

[directory]
style = "fg:on_secondary_container bg:secondary_container"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:on_secondary_container bg:secondary_container"
format = '[ $symbol $branch ]($style)'

[kubernetes]
disabled = false
symbol = ""
style = "fg:on_secondary_container bg:secondary_container"
format = '[ $symbol $context ]($style)'
contexts = [
  { context_pattern = "arn:aws:eks:(?P<region>[^:]+):(?P<account>[^:]+):cluster/(?P<name>.+)", context_alias = "$name ($region)" },
]

# START MATUGEN PALETTE
# END MATUGEN PALETTE
