source = $HOME/.config/theme/theme.conf

auth {
  pam:enabled = true
  pam:module = hyprlock
}

# GENERAL
general {
  disable_loading_bar = true
  hide_cursor = true
}

# LAYOUT
label {
  monitor =
  text = Layout: $LAYOUT
  color = $text-color
  font_size = 25
  font_family = $font
  position = 30, -30
  halign = left
  valign = top
}

# TIME
label {
  monitor =
  text = $TIME
  color = $text-color
  font_size = 90
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d.%m.%Y"
  color = $text-color
  font_size = 25
  font_family = $font
  position = -30, -150
  halign = right
  valign = top
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $border-active-color
  inner_color = $background-color
  font_color = $text-color
  fade_on_empty = false
  placeholder_text = <span foreground="##$text-color"><i>󰌾 Logged in as </i><span foreground="##$text-color">$USER</span></span>
  hide_input = false
  check_color = $text-active-color
  fail_color = $text-urgent-color
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $state-warning-color
  position = 0, -47
  halign = center
  valign = center
}
