[config]
# If set to enabled, it will check for updates when you run the matugen command, notifying you that an update is avaiable.
version_check = false

caching = false

# Changing the syntax
# Expr is for keywords like {{ <keyword> }}
expr_prefix = "{{"
expr_postfix = "}}"

# Block is for stuff like for loops etc.
block_prefix = "<*"
block_postfix = "*>"

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.lua'
output_path = '~/.config/hypr/colors.lua'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.mako]
input_path = '~/.config/matugen/templates/mako.conf'
output_path = '~/.config/mako/colors.conf'
post_hook = 'makoctl reload'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/themes/matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all matugen"

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux.conf'
output_path = '~/.config/tmux/colors.conf'
post_hook = 'tmux source-file ~/.config/tmux/colors.conf'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.zsh]
input_path = '~/.config/matugen/templates/zsh.sh'
output_path = '~/.config/zsh/theme.zsh'

[templates.lazygit]
input_path = '~/.config/matugen/templates/lazygit.yml'
output_path = '~/.config/lazygit/theme.yml'

[templates.k9s]
input_path = '~/.config/matugen/templates/k9s.yaml'
output_path = '~/.config/k9s/skins/matugen.yaml'
