[config]
# If set to enabled, it will check for updates when you run the matugen command, notifying you that an update is avaiable.
version_check = false

caching = false

# Changing the syntax
# Expr is for keywords like {{ <keyword> }}
expr_prefix = "{{"
expr_postfix = "}}"

# Block is for stuff like for loops etc.
block_prefix = "<*"
block_postfix = "*>"

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.lua'
output_path = '~/.config/hypr/colors.lua'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.mako]
input_path = '~/.config/matugen/templates/mako.conf'
output_path = '~/.config/mako/colors.conf'
post_hook = 'makoctl reload'
