#!/bin/sh

CONFIG_FOLDER=$HOME/.config/nordvpn

list_countries() {
  ls $CONFIG_FOLDER/profiles/ovpn_udp/ | cut -c 1-2 | uniq
}

connect() {
  local country=$1
  local file

  if [[ $(is_vpn_connected) = "connected" ]]
  then
    notify-send "OpenVPN is already running"
    exit 1
  fi

  if [[ -z $country ]]
  then
    file=$(ls -1 $CONFIG_FOLDER/profiles/ovpn_udp/* | shuf -n 1)
  else
    file=$(ls -1 $CONFIG_FOLDER/profiles/ovpn_udp/$country* | shuf -n 1)
  fi

  notify-send -t 2000 "Waiting for connection"

  pkexec sh -c "sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -w net.ipv6.conf.default.disable_ipv6=1 && daemonize -e $HOME/nordvpn.log -o $HOME/nordvpn.log $(which openvpn) --config $file --auth-user-pass $CONFIG_FOLDER/service-credentials"
  if [[ $? -ne 0 ]]
  then
    notify-send -u critical "Failed to connect"
    return
  fi

  local status=$(wait_for_status "connected")
  if [[ $status = "done" ]]
  then
    notify-send "Connected to NordVPN"
  else
    notify-send -u critical "Failed to connect" "$(cat $HOME/nordvpn.log)"
  fi

  rm -f nordvpn.log
}

wait_for_status() {
  local counter=0
  local desired_status=$1

  while [ ! "$(is_vpn_connected)" = "$desired_status" ]; do
    sleep 0.1
    counter=$((counter + 1))
    if [ $counter -ge 50 ]; then
      echo "error"
      return
    fi
  done

  echo "done"
}

is_vpn_connected() {
  nmcli connection show tun0 >/dev/null 2>&1
  if [ $? -eq 0 ]; then
    echo "connected"
  else
    echo "disconnected"
  fi
}

disconnect() {
  pkexec killall openvpn
  local status=$(wait_for_status "disconnected")
  if [[ $status = "done" ]]
  then
    notify-send "Disconnected from NordVPN"
  else
    notify-send -u critical "Failed to disconnect"
  fi
}

update_configurations() {
  rm -rf $CONFIG_FOLDER/profiles
  mkdir -p $CONFIG_FOLDER/profiles
  rm -f $CONFIG_FOLDER/profiles/ovpn.zip
  curl -o $CONFIG_FOLDER/profiles/ovpn.zip https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip
  unzip $CONFIG_FOLDER/profiles/ovpn.zip -d $CONFIG_FOLDER/profiles
  rm -f $CONFIG_FOLDER/profiles/ovpn.zip
}

usage() {
  echo "Usage: $0 ACTION [OPTIONS]"
  echo "Manage NordVPN connections."
  echo ""
  echo "ACTION can be any of:"
  echo " list: list countries with NordVPN servers"
  echo " connect: connects to a NordVPN"
  echo " disconnect: disconnects from NordVPN"
  echo " status: displays the NordVPN connection status"
  echo " update: downloads a new set of NordVPN configurations"
  echo ""
  echo "Options:"
  echo " -c, --country ID Connect to a VPN server in a specific country"
  echo " -h, --help       This help"
  exit 1
}

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      usage
      shift
      ;;
    -c|--country)
      COUNTRY=$2
      shift
      shift
      ;;
    *)
      ACTION=$1
      shift
      ;;
  esac
done

if [[ $ACTION = "list-countries" ]]
then
  list_countries
elif [[ $ACTION = "connect" ]]
then
  connect $COUNTRY
elif [[ $ACTION = "disconnect" ]]
then
  disconnect
elif [[ $ACTION = "status" ]]
then
  is_vpn_connected
elif [[ $ACTION = "update" ]]
then
  update_configurations
else
  echo "Unknown action $ACTION"
  exit 1
fi
