#!/bin/sh

BASE_MOUNT_POINT=/var/run/media/$USER

mount() {
  local mount_point="$BASE_MOUNT_POINT/android"

  sudo rm -rf $mount_point
  sudo mkdir -p $mount_point
  sudo chown $USER:$USER $mount_point
  aft-mtp-mount $mount_point
  if [[ $? -eq 0 ]]
  then
    echo "Android FS available at $mount_point"
    notify-send "Android FS available at $mount_point"
  else
    echo "Failed to mount Android FS on $mount_point"
    notify-send "Failed to mount Android FS on $mount_point"
  fi
}

unmount() {
  local mount_point="$BASE_MOUNT_POINT/android"

  sudo umount "$mount_point"
  if [[ $? -eq 0 ]]
  then
    echo "Android FS at $mount_point unmounted"
    notify-send "Android FS at $mount_point unmounted"
  else
    echo "Failed to unmount $mount_point"
    notify-send "Failed to unmount $mount_point"
  fi
}

usage() {
  echo "Usage: $0 ACTION [OPTIONS] NAME"
  echo "Mount and unmount Android FS."
  echo ""
  echo "ACTION can be any of:"
  echo " mount: mount a connected Android FS"
  echo " umount: unmount a mounted Android FS"
  echo ""
  echo "Options:"
  echo " -h, --help This help"
  exit 1
}

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      usage
      shift
      ;;
    *)
      ACTION=$1
      shift
      ;;
  esac
done

if [[ $ACTION = "mount" ]]
then
  mount
elif [[ $ACTION = "umount" ]]
then
  unmount
else
  echo "Unknown action $ACTION"
  exit 1
fi
