# statusbar
source -F ~/.config/theme/theme.tmux.conf
set -g status-justify left
set -g status-style 'bg=#{@background-color}'

set -g status-left ''
set -g status-left-length 10

set -g status-right ''
set -g status-right-length 10

setw -g window-status-current-format '#[fg=#{@background-color},bg=#{@module-1-background-active-color} ]#[fg=#{@module-1-text-active-color},bg=#{@module-1-background-active-color} ] #I #[fg=#{@module-1-background-active-color},bg=#{@background-color} ]'

setw -g window-status-format '#[fg=#{@background-color},bg=#{@module-1-background-inactive-color} ]#[fg=#{@module-1-text-inactive-color},bg=#{@module-1-background-inactive-color} ] #I #[fg=#{@module-1-background-inactive-color},bg=#{@background-color} ]'

# Initialize TMUX plugin manager
set -g @plugin 'tmux-plugins/tpm'
run '/usr/share/tmux-plugin-manager/tpm'
