# Generic configuration
source "$ZSH_CONFIG_HOME/config.zsh"

# History
source "$ZSH_CONFIG_HOME/history.zsh"

# Completion
source "$ZSH_CONFIG_HOME/completion.zsh"

# Key bindings
source "$ZSH_CONFIG_HOME/key-bindings.zsh"

# Prompt
source "$ZSH_CONFIG_HOME/prompt.zsh"

# Modules
source "$ZSH_CONFIG_HOME/modules/ls.zsh"
source "$ZSH_CONFIG_HOME/modules/git.zsh"
source "$ZSH_CONFIG_HOME/modules/k8s.zsh"
source "$ZSH_CONFIG_HOME/modules/docker.zsh"
source "$ZSH_CONFIG_HOME/modules/nas.zsh"
source "$ZSH_CONFIG_HOME/modules/nordvpn.zsh"
source "$ZSH_CONFIG_HOME/modules/pacman.zsh"
source "$ZSH_CONFIG_HOME/modules/lazygit.zsh"
source "$ZSH_CONFIG_HOME/modules/yazi.zsh"
