background-color={{ colors.tertiary.default.hex }}
text-color={{ colors.on_tertiary.default.hex }}

[urgency=high]
background-color={{ colors.error_container.default.hex }}
text-color={{ colors.on_error_container.default.hex }}
