background-color={{ colors.inverse_surface.default.hex }}
text-color={{ colors.inverse_on_surface.default.hex }}

[urgency=high]
background-color={{ colors.error_container.default.hex }}
text-color={{ colors.on_error_container.default.hex }}
